### ISSUE TITLE
Adding new quotes

### ISSUE THREAD

**Issue by cocoscientist** [piyler279/gex-api#3]
Some new quotes have to be added.
Quotes are located in data/quotes.json.
You can get reference for quotes from here
https://gex.fandom.com/wiki/List_of_quotes_in_Gex:_Enter_the_Gecko

**Comment by rahulSinha-01** [comment]
I'm a newbie to open source contribution and wanted to contribute in your project because i'm quite familiar with expressJS and nodeJS. So can you guide me on this a little bit. (like what the actual problem is..)

**Comment by cocoscientist** [comment]
updated the issue description, I'll update readme to make it easier to understand

**Comment by rahulSinha-01** [comment]
thanks @piyler279 . I need some time to get around your code and will fix your issue

**Comment by rahulSinha-01** [comment]
so we need to update only the data/quotes.json file right?

**Comment by rahulSinha-01** [comment]
So, we need to update all the quotes from level 'Toon TV' to  level'Rezopolis'?

**Comment by cocoscientist** [comment]
feel free to browse, if you think there's some other issue, you can add an issue

**Comment by cocoscientist** [comment]
> So, we need to update all the quotes from level 'Toon TV' to level'Rezopolis'?

I'm sorry, not like that. You can create a new object for level "Rezopolis". If you have more quotes for Toon TV or a level previously there, add them to the String array for quotes

**Comment by rahulSinha-01** [comment]
> > So, we need to update all the quotes from level 'Toon TV' to level'Rezopolis'?
> 
> I'm sorry, not like that. You can create a new object for level "Rezopolis". If you have more quotes for Toon TV or a level previously there, add them to the String array for quotes

I got it now! 
Can i contibute in this project?

**Comment by cocoscientist** [comment]
> I got it now!
> Can i contibute in this project?

Sure! Another thing, you don't need to add all quotes, as it might not be humanly possible to do so

**Comment by rahulSinha-01** [comment]
> > I got it now!
> > Can i contibute in this project?
> 
> Sure! Another thing, you don't need to add all quotes, as it might not be humanly possible to do so

Ok that's great news 😂😂
thanks once again!

**Comment by cocoscientist** [comment]
Thanks for working on this issue, I'll be closing it now
